[package]
name = "slideshow"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
simple_logger = "5.0.0"
bytemuck = "1.21.0"

pollster = "0.4.0"
winit = { version = "0.30.8", default-features = false, features = [
    "wayland",
    "rwh_06",
] }
wgpu = { version = "23.0.1", default-features = false, features = ["wgsl"] }
image = { version = "0.25.5", default-features = false, features = ["jpeg"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
